### ISSUE TITLE
Grav Site Link to Docs Broken

### ISSUE THREAD

**Issue by thekenshow** [bleutzinn/grav-plugin-form-prefiller#1]
On https://getgrav.org/downloads/plugins, the Docs link for the Form Prefiller plugin is https://github.com/bleutzinn/grav-plugin-form-prefiller/README.md but returns "not found". Likely a blueprint issue, since that's where GPM gets that link?

**Comment by bleutzinn** [comment]
Sorry for the late response. Somehow your issue slipped my attention.
It has led to a new release though :)
Thanks for pointing this out!
